# Generated by Django 5.2.7 on 2025-10-28 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de la cuenta (ej. 111, 121.01)', max_length=20, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo de la cuenta (ej. Caja General)', max_length=255)),
                ('tipo_cuenta', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio'), ('INGRESO', 'Ingreso'), ('COSTO', 'Costo'), ('GASTO', 'Gasto'), ('ORDEN', 'Cuenta de Orden')], help_text='Clasificación principal para estados financieros', max_length=10)),
                ('naturaleza', models.CharField(choices=[('DEUDORA', 'Deudora'), ('ACREEDORA', 'Acreedora')], help_text='Naturaleza de la cuenta (Deudora o Acreedora)', max_length=10)),
                ('es_imputable', models.BooleanField(default=False, help_text='Indica si la cuenta puede recibir movimientos (transacciones)')),
                ('padre', models.ForeignKey(blank=True, help_text='Cuenta padre a la que pertenece esta subcuenta', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijos', to='contabilidad.cuenta')),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Catálogo de Cuentas',
                'ordering': ['codigo'],
            },
        ),
    ]
