# Generated by Django 5.2.7 on 2025-10-28 21:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_cargar_catalogo_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del período (ej. Enero 2024)', max_length=100, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=10)),
            ],
            options={
                'verbose_name': 'Período Contable',
                'verbose_name_plural': 'Períodos Contables',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='AsientoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_partida', models.PositiveIntegerField(editable=False, help_text='Número de partida correlativo dentro del período')),
                ('fecha', models.DateField(default=django.utils.timezone.now, help_text='Fecha de la transacción')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del asiento (concepto, glosa)')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos_creados', to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asientos', to='contabilidad.periodocontable')),
            ],
            options={
                'verbose_name': 'Asiento Diario',
                'verbose_name_plural': 'Libro Diario',
                'ordering': ['periodo', 'numero_partida'],
                'unique_together': {('periodo', 'numero_partida')},
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('asiento', models.ForeignKey(help_text='Asiento al que pertenece este movimiento', on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='contabilidad.asientodiario')),
                ('cuenta', models.ForeignKey(help_text='Cuenta contable afectada', limit_choices_to={'es_imputable': True}, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cuenta')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['pk'],
            },
        ),
    ]
