# Generated by Django 5.0 on 2025-11-02 07:00
# Este archivo crea los grupos de roles y los usuarios iniciales.

from django.db import migrations
from django.contrib.auth.hashers import make_password

def crear_grupos_y_usuarios(apps, schema_editor):
    """
    Crea los grupos de roles y los usuarios iniciales con contraseñas
    y asignaciones de grupo, asegurando la idempotencia.
    """
    # Obtener los modelos en el contexto de esta migración
    User = apps.get_model('auth', 'User')
    Group = apps.get_model('auth', 'Group')
    
    # --- 1. Crear Grupos ---
    grupo_admin, _ = Group.objects.get_or_create(name='Administrador')
    grupo_contador, _ = Group.objects.get_or_create(name='Contador')
    grupo_informatico, _ = Group.objects.get_or_create(name='Informático')

    # --- 2. Definir Usuarios ---
    # Contraseña genérica para todos (¡Cambiar en producción!)
    PASSWORD_DEFAULT = "Softnova2025*" 
    
    # Hashear la contraseña una sola vez
    hashed_password = make_password(PASSWORD_DEFAULT)

    usuarios = [
        # Administradores
        {
            'username': 'gerente.admin',
            'email': 'gerente.admin@softnova.sv',
            'first_name': 'Gerente',
            'last_name': 'Administrativo',
            'grupo': grupo_admin,
            'is_staff': True, # Para que puedan entrar al /admin
            'is_superuser': True # Los admins son superusuarios
        },
        {
            'username': 'analista.fin',
            'email': 'analista.fin@softnova.sv',
            'first_name': 'Analista',
            'last_name': 'Financiero',
            'grupo': grupo_admin,
            'is_staff': True,
            'is_superuser': True
        },
        # Contador
        {
            'username': 'contador.softnova',
            'email': 'contador@softnova.sv',
            'first_name': 'Contador',
            'last_name': 'General',
            'grupo': grupo_contador,
            'is_staff': True, # Staff para que el decorador lo reconozca
            'is_superuser': False # No es superusuario
        },
        # Informático
        {
            'username': 'jefe.proyectos',
            'email': 'jefe.proyectos@softnova.sv',
            'first_name': 'Jefe de',
            'last_name': 'Proyectos',
            'grupo': grupo_informatico,
            'is_staff': False, # No necesita entrar al /admin
            'is_superuser': False
        }
    ]

    # --- 3. Crear Usuarios ---
    for data_usuario in usuarios:
        grupo = data_usuario.pop('grupo')
        
        # Verificar si el usuario ya existe
        usuario, creado = User.objects.get_or_create(
            username=data_usuario['username'],
            defaults={
                'email': data_usuario['email'],
                'password': hashed_password,
                'first_name': data_usuario['first_name'],
                'last_name': data_usuario['last_name'],
                'is_staff': data_usuario.get('is_staff', False),
                'is_superuser': data_usuario.get('is_superuser', False)
            }
        )
        
        # Si fue recién creado, asignar grupo. Si ya existía, también asegurar grupo.
        if creado:
            print(f"Usuario '{usuario.username}' creado con contraseña por defecto.")
        
        # Asegurar que el usuario esté en el grupo correcto
        usuario.groups.add(grupo)
        
        # Si el usuario ya existía pero no tenía la contraseña correcta
        # (para desarrollo, esto es útil)
        if not creado:
            # Forzar la actualización de la contraseña por si cambió
            if not usuario.check_password(PASSWORD_DEFAULT):
                usuario.set_password(PASSWORD_DEFAULT)
                usuario.save()
                print(f"Contraseña de '{usuario.username}' actualizada.")
            else:
                 print(f"Usuario '{data_usuario['username']}' ya existía, grupo verificado.")


class Migration(migrations.Migration):

    # Depende de tu última migración (según tu captura)
    dependencies = [
        ('contabilidad', '0003_periodocontable_asientodiario_movimiento'),
    ]

    operations = [
        migrations.RunPython(crear_grupos_y_usuarios),
    ]

