# Generated by Django 5.2.7 on 2025-11-02 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_crear_grupos_y_usuarios_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientodiario',
            name='es_asiento_automatico',
            field=models.BooleanField(default=False, help_text='Indica si es un asiento de Cierre o Apertura generado por el sistema.'),
        ),
        migrations.AddField(
            model_name='periodocontable',
            name='asiento_apertura_siguiente',
            field=models.ForeignKey(blank=True, help_text='Asiento de Apertura (Balance) creado para el *siguiente* período.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodo_abierto_por', to='contabilidad.asientodiario'),
        ),
        migrations.AddField(
            model_name='periodocontable',
            name='asiento_cierre',
            field=models.ForeignKey(blank=True, help_text='Asiento de Cierre (Resultados) de este período.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodo_cerrado_por', to='contabilidad.asientodiario'),
        ),
    ]
