# Generated by Django 5.2.7 on 2025-11-03 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_asientodiario_es_asiento_automatico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='esta_activa',
            field=models.BooleanField(default=True, help_text='Indica si la cuenta está activa. Las cuentas inactivas no se pueden usar en nuevos asientos.'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cuenta',
            field=models.ForeignKey(help_text='Cuenta contable afectada', limit_choices_to={'es_imputable': True, 'esta_activa': True}, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cuenta'),
        ),
    ]
