# Generated by Django 5.2.7 on 2025-10-28 20:37

from django.db import migrations

def cargar_catalogo(apps, schema_editor):
    """
    Carga el catálogo de cuentas de SoftNova S.A de C.V
    """
    Cuenta = apps.get_model('contabilidad', 'Cuenta')

    # --- 1. ACTIVO ---
    activo = Cuenta.objects.create(
        codigo='1', nombre='ACTIVO', 
        tipo_cuenta='ACTIVO', naturaleza='DEUDORA', es_imputable=False
    )
    
    # 11 Caja y Bancos
    caja_bancos = Cuenta.objects.create(
        codigo='11', nombre='Caja y Bancos', padre=activo,
        tipo_cuenta='ACTIVO', naturaleza='DEUDORA', es_imputable=False
    )
    Cuenta.objects.create(
        codigo='111', nombre='Caja General', padre=caja_bancos,
        tipo_cuenta='ACTIVO', naturaleza='DEUDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='112', nombre='Fondo Fijo de Caja Chica', padre=caja_bancos,
        tipo_cuenta='ACTIVO', naturaleza='DEUDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='113', nombre='Banco Local - Cuenta Corriente', padre=caja_bancos,
        tipo_cuenta='ACTIVO', naturaleza='DEUDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='114', nombre='Banco Local - Cuenta de Ahorros', padre=caja_bancos,
        tipo_cuenta='ACTIVO', naturaleza='DEUDORA', es_imputable=True
    )

    # 12 Cuentas por Cobrar
    cxc = Cuenta.objects.create(
        codigo='12', nombre='Cuentas por Cobrar', padre=activo,
        tipo_cuenta='ACTIVO', naturaleza='DEUDORA', es_imputable=False
    )
    Cuenta.objects.create(
        codigo='121', nombre='Clientes Locales', padre=cxc,
        tipo_cuenta='ACTIVO', naturaleza='DEUDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='122', nombre='Clientes del Exterior', padre=cxc,
        tipo_cuenta='ACTIVO', naturaleza='DEUDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='123', nombre='Deudores Diversos', padre=cxc,
        tipo_cuenta='ACTIVO', naturaleza='DEUDORA', es_imputable=True
    )

    # 13 Anticipos y Pagos Anticipados
    anticipos = Cuenta.objects.create(
        codigo='13', nombre='Anticipos y Pagos Anticipados', padre=activo,
        tipo_cuenta='ACTIVO', naturaleza='DEUDORA', es_imputable=False
    )
    Cuenta.objects.create(
        codigo='131', nombre='Anticipos a Proveedores', padre=anticipos,
        tipo_cuenta='ACTIVO', naturaleza='DEUDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='132', nombre='Pagos Anticipados de Servicios', padre=anticipos,
        tipo_cuenta='ACTIVO', naturaleza='DEUDORA', es_imputable=True
    )

    # 14 Créditos Fiscales
    creditos_fiscales = Cuenta.objects.create(
        codigo='14', nombre='Créditos Fiscales', padre=activo,
        tipo_cuenta='ACTIVO', naturaleza='DEUDORA', es_imputable=False
    )
    Cuenta.objects.create(
        codigo='141', nombre='IVA Crédito Fiscal', padre=creditos_fiscales,
        tipo_cuenta='ACTIVO', naturaleza='DEUDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='142', nombre='Retenciones por Cobrar', padre=creditos_fiscales,
        tipo_cuenta='ACTIVO', naturaleza='DEUDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='143', nombre='Percepciones por Cobrar', padre=creditos_fiscales,
        tipo_cuenta='ACTIVO', naturaleza='DEUDORA', es_imputable=True
    )

    # 15 Propiedad, Planta y Equipo
    ppe = Cuenta.objects.create(
        codigo='15', nombre='Propiedad, Planta y Equipo', padre=activo,
        tipo_cuenta='ACTIVO', naturaleza='DEUDORA', es_imputable=False
    )
    Cuenta.objects.create(
        codigo='151', nombre='Mobiliario y Equipo de Oficina', padre=ppe,
        tipo_cuenta='ACTIVO', naturaleza='DEUDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='152', nombre='Equipo de Computación', padre=ppe,
        tipo_cuenta='ACTIVO', naturaleza='DEUDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='153', nombre='Vehículos', padre=ppe,
        tipo_cuenta='ACTIVO', naturaleza='DEUDORA', es_imputable=True
    )
    # NOTA: Contra-cuenta de Activo, naturaleza Acreedora
    Cuenta.objects.create(
        codigo='154', nombre='Depreciación Acumulada', padre=ppe,
        tipo_cuenta='ACTIVO', naturaleza='ACREEDORA', es_imputable=True
    )

    # 16 Activos Intangibles
    intangibles = Cuenta.objects.create(
        codigo='16', nombre='Activos Intangibles', padre=activo,
        tipo_cuenta='ACTIVO', naturaleza='DEUDORA', es_imputable=False
    )
    Cuenta.objects.create(
        codigo='161', nombre='Software Desarrollado Internamente', padre=intangibles,
        tipo_cuenta='ACTIVO', naturaleza='DEUDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='162', nombre='Licencias y Derechos de Uso', padre=intangibles,
        tipo_cuenta='ACTIVO', naturaleza='DEUDORA', es_imputable=True
    )
    # NOTA: Contra-cuenta de Activo, naturaleza Acreedora
    Cuenta.objects.create(
        codigo='163', nombre='Amortización Acumulada de Intangibles', padre=intangibles,
        tipo_cuenta='ACTIVO', naturaleza='ACREEDORA', es_imputable=True
    )

    # 17 Depósitos en Garantía
    depositos = Cuenta.objects.create(
        codigo='17', nombre='Depósitos en Garantía', padre=activo,
        tipo_cuenta='ACTIVO', naturaleza='DEUDORA', es_imputable=True # Es imputable directamente
    )

    # --- 2. PASIVO ---
    pasivo = Cuenta.objects.create(
        codigo='2', nombre='PASIVO', 
        tipo_cuenta='PASIVO', naturaleza='ACREEDORA', es_imputable=False
    )

    # 21 Cuentas por Pagar
    cxp = Cuenta.objects.create(
        codigo='21', nombre='Cuentas por Pagar', padre=pasivo,
        tipo_cuenta='PASIVO', naturaleza='ACREEDORA', es_imputable=False
    )
    Cuenta.objects.create(
        codigo='211', nombre='Proveedores Locales para equipo de Empresa', padre=cxp,
        tipo_cuenta='PASIVO', naturaleza='ACREEDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='212', nombre='Proveedores del Exterior para equipo de Empresa', padre=cxp,
        tipo_cuenta='PASIVO', naturaleza='ACREEDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='213', nombre='Acreedores Diversos servicios para Empresa', padre=cxp,
        tipo_cuenta='PASIVO', naturaleza='ACREEDORA', es_imputable=True
    )

    # 22 Obligaciones Fiscales
    oblig_fiscales = Cuenta.objects.create(
        codigo='22', nombre='Obligaciones Fiscales', padre=pasivo,
        tipo_cuenta='PASIVO', naturaleza='ACREEDORA', es_imputable=False
    )
    Cuenta.objects.create(
        codigo='221', nombre='IVA Débito Fiscal', padre=oblig_fiscales,
        tipo_cuenta='PASIVO', naturaleza='ACREEDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='222', nombre='Retenciones por Pagar', padre=oblig_fiscales,
        tipo_cuenta='PASIVO', naturaleza='ACREEDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='223', nombre='Renta por Pagar', padre=oblig_fiscales,
        tipo_cuenta='PASIVO', naturaleza='ACREEDORA', es_imputable=True
    )

    # 23 Obligaciones Laborales
    oblig_laborales = Cuenta.objects.create(
        codigo='23', nombre='Obligaciones Laborales', padre=pasivo,
        tipo_cuenta='PASIVO', naturaleza='ACREEDORA', es_imputable=False
    )
    Cuenta.objects.create(
        codigo='231', nombre='Sueldos y Salarios por Pagar', padre=oblig_laborales,
        tipo_cuenta='PASIVO', naturaleza='ACREEDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='232', nombre='AFP por Pagar', padre=oblig_laborales,
        tipo_cuenta='PASIVO', naturaleza='ACREEDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='233', nombre='ISSS por Pagar', padre=oblig_laborales,
        tipo_cuenta='PASIVO', naturaleza='ACREEDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='234', nombre='Vacaciones y Aguinaldos Acumulados', padre=oblig_laborales,
        tipo_cuenta='PASIVO', naturaleza='ACREEDORA', es_imputable=True
    )
    
    # 24 Anticipos de Clientes
    anticipos_clientes = Cuenta.objects.create(
        codigo='24', nombre='Anticipos de Clientes', padre=pasivo,
        tipo_cuenta='PASIVO', naturaleza='ACREEDORA', es_imputable=True # Es imputable
    )

    # 25 Préstamos y Arrendamientos
    prestamos = Cuenta.objects.create(
        codigo='25', nombre='Préstamos y Arrendamientos', padre=pasivo,
        tipo_cuenta='PASIVO', naturaleza='ACREEDORA', es_imputable=False
    )
    Cuenta.objects.create(
        codigo='251', nombre='Préstamos Bancarios', padre=prestamos,
        tipo_cuenta='PASIVO', naturaleza='ACREEDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='252', nombre='Arrendamientos Financieros', padre=prestamos,
        tipo_cuenta='PASIVO', naturaleza='ACREEDORA', es_imputable=True
    )

    # --- 3. PATRIMONIO ---
    patrimonio = Cuenta.objects.create(
        codigo='3', nombre='PATRIMONIO', 
        tipo_cuenta='PATRIMONIO', naturaleza='ACREEDORA', es_imputable=False
    )
    Cuenta.objects.create(
        codigo='31', nombre='Capital Social', padre=patrimonio,
        tipo_cuenta='PATRIMONIO', naturaleza='ACREEDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='32', nombre='Reserva Legal', padre=patrimonio,
        tipo_cuenta='PATRIMONIO', naturaleza='ACREEDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='33', nombre='Resultados Acumulados', padre=patrimonio,
        tipo_cuenta='PATRIMONIO', naturaleza='ACREEDORA', es_imputable=True # O deudora si hay pérdida
    )
    Cuenta.objects.create(
        codigo='34', nombre='Utilidad o Pérdida del Ejercicio', padre=patrimonio,
        tipo_cuenta='PATRIMONIO', naturaleza='ACREEDORA', es_imputable=True # O deudora
    )

    # --- 4. INGRESOS ---
    ingresos = Cuenta.objects.create(
        codigo='4', nombre='INGRESOS', 
        tipo_cuenta='INGRESO', naturaleza='ACREEDORA', es_imputable=False
    )
    Cuenta.objects.create(
        codigo='41', nombre='Ventas de Software a la Medida', padre=ingresos,
        tipo_cuenta='INGRESO', naturaleza='ACREEDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='42', nombre='Servicios de Soporte y Mantenimiento', padre=ingresos,
        tipo_cuenta='INGRESO', naturaleza='ACREEDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='43', nombre='Instalación y Configuración de Software', padre=ingresos,
        tipo_cuenta='INGRESO', naturaleza='ACREEDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='44', nombre='Ingresos por Capacitación y Manuales de Usuario', padre=ingresos,
        tipo_cuenta='INGRESO', naturaleza='ACREEDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='45', nombre='Ingresos Financieros', padre=ingresos,
        tipo_cuenta='INGRESO', naturaleza='ACREEDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='46', nombre='Otros Ingresos Diversos', padre=ingresos,
        tipo_cuenta='INGRESO', naturaleza='ACREEDORA', es_imputable=True
    )

    # --- 5. COSTOS Y GASTOS ---
    costos_gastos = Cuenta.objects.create(
        codigo='5', nombre='COSTOS Y GASTOS', 
        tipo_cuenta='COSTO', naturaleza='DEUDORA', es_imputable=False # Tipo genérico, puede ser COSTO o GASTO
    )

    # 51 Costos
    costos = Cuenta.objects.create(
        codigo='51', nombre='Costos', padre=costos_gastos,
        tipo_cuenta='COSTO', naturaleza='DEUDORA', es_imputable=False
    )
    Cuenta.objects.create(
        codigo='511', nombre='Mano de Obra Directa', padre=costos,
        tipo_cuenta='COSTO', naturaleza='DEUDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='512', nombre='Costos de Licencias y Herramientas de Desarrollo', padre=costos,
        tipo_cuenta='COSTO', naturaleza='DEUDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='513', nombre='Costos de Soporte Técnico', padre=costos,
        tipo_cuenta='COSTO', naturaleza='DEUDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='514', nombre='Costos de Infraestructura Tecnológica', padre=costos,
        tipo_cuenta='COSTO', naturaleza='DEUDORA', es_imputable=True
    )

    # 52 Gastos
    gastos = Cuenta.objects.create(
        codigo='52', nombre='Gastos', padre=costos_gastos,
        tipo_cuenta='GASTO', naturaleza='DEUDORA', es_imputable=False
    )
    # Rellenar con todos los gastos del 521 al 532
    Cuenta.objects.create(
        codigo='521', nombre='Sueldos', padre=gastos,
        tipo_cuenta='GASTO', naturaleza='DEUDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='522', nombre='Servicios Profesionales', padre=gastos,
        tipo_cuenta='GASTO', naturaleza='DEUDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='523', nombre='Alquiler de Oficina', padre=gastos,
        tipo_cuenta='GASTO', naturaleza='DEUDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='524', nombre='Servicios Básicos de empresa', padre=gastos,
        tipo_cuenta='GASTO', naturaleza='DEUDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='525', nombre='Papelería y Útiles', padre=gastos,
        tipo_cuenta='GASTO', naturaleza='DEUDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='526', nombre='Depreciación y Amortización', padre=gastos,
        tipo_cuenta='GASTO', naturaleza='DEUDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='527', nombre='Mantenimiento de Equipos', padre=gastos,
        tipo_cuenta='GASTO', naturaleza='DEUDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='528', nombre='Gastos por Garantía y Soporte Postventa', padre=gastos,
        tipo_cuenta='GASTO', naturaleza='DEUDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='529', nombre='Publicidad y Promoción Digital', padre=gastos,
        tipo_cuenta='GASTO', naturaleza='DEUDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='530', nombre='Comisiones por Ventas', padre=gastos,
        tipo_cuenta='GASTO', naturaleza='DEUDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='531', nombre='Intereses Bancarios', padre=gastos,
        tipo_cuenta='GASTO', naturaleza='DEUDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='532', nombre='Comisiones Bancarias', padre=gastos,
        tipo_cuenta='GASTO', naturaleza='DEUDORA', es_imputable=True
    )

    # --- 6. CUENTAS DE ORDEN ---
    orden = Cuenta.objects.create(
        codigo='6', nombre='CUENTAS DE ORDEN', 
        tipo_cuenta='ORDEN', naturaleza='DEUDORA', es_imputable=False
    )
    Cuenta.objects.create(
        codigo='61', nombre='Contratos de Desarrollo en Ejecución', padre=orden,
        tipo_cuenta='ORDEN', naturaleza='DEUDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='62', nombre='Licencias en Prueba o Demo Entregadas', padre=orden,
        tipo_cuenta='ORDEN', naturaleza='DEUDORA', es_imputable=True
    )
    Cuenta.objects.create(
        codigo='63', nombre='Documentación Técnica en Proceso', padre=orden,
        tipo_cuenta='ORDEN', naturaleza='DEUDORA', es_imputable=True
    )


def deshacer_carga(apps, schema_editor):
    """
    Elimina los datos cargados si se revierte la migración.
    """
    Cuenta = apps.get_model('contabilidad', 'Cuenta')
    Cuenta.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'), # Asegúrate que esta es tu migración anterior
    ]

    operations = [
        migrations.RunPython(cargar_catalogo, deshacer_carga),
    ]

