# Generated by Django 5.2.7 on 2025-11-10 04:50

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_cuenta_esta_activa_alter_movimiento_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarioEstimadoMODAnual',
            fields=[
                ('periodo', models.OneToOneField(help_text='Período contable al que aplica este salario.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='contabilidad.periodocontable')),
                ('descripcion', models.CharField(default='SalarioEstimadoMODAnual', max_length=255)),
                ('salario', models.DecimalField(decimal_places=2, help_text='Salario Anual Estimado (Ej. 126,000.00)', max_digits=12)),
                ('mod_unitario', models.DecimalField(blank=True, decimal_places=4, editable=False, help_text='Costo por hora (MOD Unitario) calculado automáticamente.', max_digits=12, null=True)),
            ],
            options={
                'verbose_name': 'Configuración Salario MOD Anual',
                'verbose_name_plural': 'Configuraciones Salario MOD Anual',
            },
        ),
        migrations.CreateModel(
            name='CosteoProyecto',
            fields=[
                ('idCosteo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_proyecto', models.TextField(blank=True, null=True)),
                ('horas_esfuerzo', models.DecimalField(decimal_places=2, help_text='Horas de esfuerzo ingresadas para el proyecto (Ej. 320)', max_digits=10)),
                ('cif', models.DecimalField(decimal_places=2, help_text='Costo Indirecto de Fabricación asignado (Ej. 309.87)', max_digits=12)),
                ('mod_unitario', models.DecimalField(decimal_places=4, editable=False, help_text='Costo MOD por hora (obtenido de la config. del período)', max_digits=12)),
                ('factor_suma', models.DecimalField(decimal_places=10, editable=False, help_text='Suma de todos los factores CIF del período', max_digits=15)),
                ('mod_total', models.DecimalField(decimal_places=2, editable=False, help_text='MOD Unitario * Horas de Esfuerzo', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, editable=False, help_text='Costo total del proyecto (MOD Total + CIF)', max_digits=14)),
                ('periodo', models.ForeignKey(help_text='Período de configuración que usará este costeo.', on_delete=django.db.models.deletion.PROTECT, to='contabilidad.periodocontable')),
            ],
            options={
                'verbose_name': 'Costeo de Proyecto',
                'verbose_name_plural': 'Costeos de Proyectos',
                'ordering': ['-periodo', '-idCosteo'],
            },
        ),
        migrations.CreateModel(
            name='CostoIndirectoAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del CIF Específico (Ej. Alquiler o Renta de Oficinas)', max_length=255)),
                ('categoria', models.CharField(choices=[('PRODUCCION', 'Costo General de Produccion'), ('POSTVENTA', 'Costos Prostventa'), ('MANO_OBRA_IND', 'Mano de Obra Indirecta'), ('MATERIALES_SUM', 'Materiales y Suministros Indirectos'), ('OTRO', 'Otro')], default='OTRO', max_length=100)),
                ('costo_anual_estimado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo Anual Estimado para este ítem.', max_digits=12)),
                ('factor', models.DecimalField(blank=True, decimal_places=10, editable=False, help_text='Factor calculado (Costo Anual / Salario MOD Anual)', max_digits=15, null=True)),
                ('periodo', models.ForeignKey(help_text='Período contable al que aplica este costo.', on_delete=django.db.models.deletion.CASCADE, related_name='costos_indirectos', to='contabilidad.periodocontable')),
            ],
            options={
                'verbose_name': 'Costo Indirecto Anual (CIF)',
                'verbose_name_plural': 'Costos Indirectos Anuales (CIF)',
                'unique_together': {('periodo', 'nombre')},
            },
        ),
    ]
